image: maven:latest

build:
  stage: build
  script:
    - cd zooApplication
    - mvn compile
  only:
    - master
    
test:
  stage: test
  script:
    - cd zooApplication
    - mvn test
  only:
    - master