stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn compile
  only:
    - master
    - heroku-deploy

test:
  stage: test
  image: maven:latest
  script:
    - mvn test
  only:
    - master
    - heroku-deploy

deploy:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - heroku-deploy
